const SETTINGS_INIT = 'settings/SETTINGS_INIT'
const LIBRARY_UPDATE_START = 'settings/LIBRARY_UPDATE_START'
const LIBRARY_UPDATE_SUCCESS = 'settings/LIBRARY_UPDATE_SUCCESS'
const LIBRARY_UPDATE_FAILURE = 'settings/LIBRARY_UPDATE_FAILURE'
const LIBRARY_ERASE_START = 'settings/LIBRARY_ERASE_START'
const LIBRARY_ERASE_SUCCESS = 'settings/LIBRARY_ERASE_SUCCESS'
const LIBRARY_ERASE_FAILURE = 'settings/LIBRARY_ERASE_FAILURE'
const SET_THEME = 'settings/SET_THEME'

export default {
  SETTINGS_INIT,
  LIBRARY_UPDATE_START,
  LIBRARY_UPDATE_SUCCESS,
  LIBRARY_UPDATE_FAILURE,
  LIBRARY_ERASE_START,
  LIBRARY_ERASE_SUCCESS,
  LIBRARY_ERASE_FAILURE,
  SET_THEME,
}
