const SETTINGS_INIT = 'SETTINGS_INIT'
const LIBRARY_UPDATE_START = 'LIBRARY_UPDATE_START'
const LIBRARY_UPDATE_SUCCESS = 'LIBRARY_UPDATE_SUCCESS'
const LIBRARY_UPDATE_FAILURE = 'LIBRARY_UPDATE_FAILURE'
const LIBRARY_ERASE_START = 'LIBRARY_ERASE_START'
const LIBRARY_ERASE_SUCCESS = 'LIBRARY_ERASE_SUCCESS'
const LIBRARY_ERASE_FAILURE = 'LIBRARY_ERASE_FAILURE'

export default {
  SETTINGS_INIT,
  LIBRARY_UPDATE_START,
  LIBRARY_UPDATE_SUCCESS,
  LIBRARY_UPDATE_FAILURE,
  LIBRARY_ERASE_START,
  LIBRARY_ERASE_SUCCESS,
  LIBRARY_ERASE_FAILURE,
}
