const PLAYLIST_SELECT_PLAYLIST = 'playlist/SELECT_PLAYLIST'
const PLAYLIST_ADD_PLAYLIST = 'playlist/ADD_PLAYLIST'
const PLAYLIST_REMOVE_PLAYLIST = 'playlist/PLAYLIST_REMOVE_PLAYLIST'

const PLAYLIST_ADD_TRACK = 'playlist/ADD_TRACK'
const PLAYLIST_REMOVE_TRACK = 'playlist/REMOVE_TRACK'

export default {
  PLAYLIST_SELECT_PLAYLIST,
  PLAYLIST_ADD_PLAYLIST,
  PLAYLIST_REMOVE_PLAYLIST,
  PLAYLIST_ADD_TRACK,
  PLAYLIST_REMOVE_TRACK,
}
