const PLAYLIST_SELECT_PLAYLIST = 'playlist/SELECT_PLAYLIST'
const PLAYLIST_CREATE_PLAYLIST = 'playlist/CREATE_PLAYLIST'
const PLAYLIST_REMOVE_PLAYLIST = 'playlist/REMOVE_PLAYLIST'

const PLAYLIST_SELECT_TRACK = 'playlist/SELECT_TRACK'
const PLAYLIST_REMOVE_TRACK = 'playlist/REMOVE_TRACK'
const PLAYLIST_ADD_TRACK = 'playlist/ADD_TRACK'
const PLAYLIST_ADD_ALBUM = 'playlist/ADD_ALBUM'
const PLAYLIST_ADD_ARTIST = 'playlist/ADD_ARTIST'
const PLAYLIST_ADD_PLAYLIST = 'playlist/ADD_PLAYLIST'

const PLAYLIST_UPDATE_TRACKS = 'playlist/PLAYLIST_UPDATE_TRACKS'
const PLAYLIST_UPDATE_INFO = 'playlist/PLAYLIST_UPDATE_INFO'

export default {
  PLAYLIST_SELECT_PLAYLIST,
  PLAYLIST_CREATE_PLAYLIST,
  PLAYLIST_REMOVE_PLAYLIST,
  PLAYLIST_SELECT_TRACK,
  PLAYLIST_REMOVE_TRACK,
  PLAYLIST_ADD_TRACK,
  PLAYLIST_ADD_ALBUM,
  PLAYLIST_ADD_ARTIST,
  PLAYLIST_ADD_PLAYLIST,
  PLAYLIST_UPDATE_TRACKS,
  PLAYLIST_UPDATE_INFO,
}
