const PLAYER_TOGGLE_PLAY_PAUSE = 'PLAYER_TOGGLE_PLAY_PAUSE'
const PLAYER_TOGGLE_SHUFFLE = 'PLAYER_TOGGLE_SHUFFLE'
const PLAYER_TOGGLE_REPEAT = 'PLAYER_TOGGLE_REPEAT'
const PLAYER_SET_VOLUME = 'PLAYER_SET_VOLUME'
const PLAYER_SET_TRACK = 'PLAYER_SET_TRACK'
const PLAYER_SET_DURATION = 'PLAYER_SET_DURATION'
const PLAYER_SET_PROGRESS = 'PLAYER_SET_PROGRESS'

const QUEUE_ADD_TRACK = 'QUEUE_ADD_TRACK'
const QUEUE_ADD_ALBUM = 'QUEUE_ADD_ALBUM'
const QUEUE_ADD_ARTIST = 'QUEUE_ADD_ARTIST'
const QUEUE_REMOVE_TRACK = 'QUEUE_REMOVE_TRACK'
const QUEUE_CLEAR = 'QUEUE_CLEAR'
const QUEUE_UPDATE = 'QUEUE_UPDATE'
const QUEUE_SET_CURRENT = 'QUEUE_SET_CURRENT'

export default {
  PLAYER_TOGGLE_PLAY_PAUSE,
  PLAYER_TOGGLE_SHUFFLE,
  PLAYER_TOGGLE_REPEAT,
  PLAYER_SET_VOLUME,
  PLAYER_SET_TRACK,
  PLAYER_SET_DURATION,
  PLAYER_SET_PROGRESS,
  QUEUE_ADD_TRACK,
  QUEUE_ADD_ALBUM,
  QUEUE_ADD_ARTIST,
  QUEUE_REMOVE_TRACK,
  QUEUE_CLEAR,
  QUEUE_UPDATE,
  QUEUE_SET_CURRENT,
}
